config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/for-the-eyes-of-jamison' => 'static_pages#hello_jamison'
  get "/.well-known/acme-challenge/#{ENV['LETSENCRYPTVERIFYROUTE1']}" => 'static_pages#letsencrypt1'
  get "/.well-known/acme-challenge/#{ENV['LETSENCRYPTVERIFYROUTE2']}" => 'static_pages#letsencrypt2'

  namespace :admin do
    resources :projects
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  layout "admin"
  http_basic_authenticate_with name: ENV['HTTP_USERNAME'], password: ENV['HTTP_PASSWORD']
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /admin/projects
  # GET /admin/projects.json
  def index
    @projects = Project.all
  end

  # GET /admin/projects/1
  # GET /admin/projects/1.json
  def show
  end

  # GET /admin/projects/new
  def new
    @project = Project.new
  end

  # GET /admin/projects/1/edit
  def edit
  end

  # POST /admin/projects
  # POST /admin/projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/projects/1
  # PATCH/PUT /admin/projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/projects/1
  # DELETE /admin/projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params[:project]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @project = Project.first
  end

  def hello_jamison; end

  def letsencrypt1
    render text: ENV['LETSENCRYPTKEY1']
  end

  def letsencrypt2
    render text: ENV['LETSENCRYPTKEY2']
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/projects/_form.html.erb
<%= form_for([:admin, @project]) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/projects/edit.html.erb
<h1>Editing Admin Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_project %> |
<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Projects</h1>

<table>
  <thead>
    <tr>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to 'Show', admin_project_path(project) %></td>
        <td><%= link_to 'Edit', edit_admin_project_path(project) %></td>
        <td><%= link_to 'Destroy', admin_project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_admin_project_path %>

app/views/admin/projects/new.html.erb
<h1>New Admin Project</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_project_path(@admin_project) %> |
<%= link_to 'Back', admin_projects_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Section</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link href='https://fonts.googleapis.com/css?family=Lato:100,400,900' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" href="<%= request.base_url %>/favicon.ico">
  </head>

  <body>
    <%= yield %>
  </body>

  <footer>
  </footer>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lte IE 9]><html class="no-js lt-ie10"><![endif]-->
<!--[if gt IE 9]><!--><html class="no-js"><!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Hello, I'm David.</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link href='https://fonts.googleapis.com/css?family=Lato:100,400,900' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" href="<%= request.base_url %>/favicon.ico">
    <link type="text/css" rel="stylesheet" href="/assets/css/style.css" media="screen">
  </head>

  <body class='<%= "#{controller_name}-#{action_name}" %>'>
    <% if Rails.env.production? %>
      <!-- Google Tag Manager -->
      <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-WSVX49"height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript> <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-WSVX49');</script><!-- End Google Tag Manager -->
    <% end %>

    <%= yield %>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script type="text/javascript" src="/assets/js/main.js"></script>
  </body>
</html>

app/views/static_pages/hello_jamison.html.erb
<marquee scrollamount="500" scrolldelay="500">
  Good Morning, Jamison!
 </marquee>

app/views/static_pages/home.html.erb
<script>
  window.config = window.config || {};
  window.config.maker_words = '<%= raw %w( systems programs software websites things solutions ).to_json %>';
  window.config.tools_words = '<%= raw ["Ruby", "Ruby on Rails", "Sinatra", "RSpec", "HTML", "SCSS", "JavaScript", "AJAX", "jQuery", "JRuby", "CoffeScript", "C++", "Java", "Bash", "PHP", "JSON/XML", "Redis", "PostgreSQL", "Vim", "Git", "Laravel", "Wordpress"].to_json %> '
</script>


<div id="splash-screen" class="section">
  <span class="inner-text">
    <span class="keyword"></span><span class="other-words"></span>
  </span>

  <a href="#maker-of-things" class="next-section">
    <span class="icon-arrow-down"></span>
    <span>More</span>
  </a>
</div>

<div id="maker-of-things" class="section">
  <span class="inner-text">I'm a maker of</span>
  <span class="keyword"></span>

  <a href="#make-things-with" class="next-section">
    <span class="icon-arrow-down"></span>
    <span>More</span>
  </a>
</div>

<div id="make-things-with" class="section">
  <span class="inner-text">I make things with</span>
  <span class="keyword"></span>

  <a href="#things-made" class="next-section">
    <span class="icon-arrow-down"></span>
    <span>More</span>
  </a>
</div>

<div id="things-made" class="section">
    <!-- <span class="inner-text"> Here are some things I've made.</span> -->
    <div class="project-wrapper">
      <img class="monitor" src="/assets/images/monitor.png">
      <img class="in-monitor" src="<%= @project[:image_url] %>">
    </div>

  <a href="#details" class="next-section">
    <span class="icon-arrow-down"></span>
    <span>More</span>
  </a>
</div>

<div id="details" class="section">
  <span class="inner-text"> Everything else. </span>
  <ul class="icon-wrapper">
    <li class="icon">
      <a target="_blank" href="https://twitter.com/extremedavidh"> <span class="icon-twitter"></span></a>
    </li>

    <li class="icon">
      <a target="_blank" href="https://github.com/dhahn"> <span class="icon-github"></span></a>
    </li>

    <li class="icon">
      <a target="_blank" href="https://www.facebook.com/davidmhahn"> <span class="icon-facebook"></span></a>
    </li>

    <li class="icon">
      <a target="_blank" href="https://www.linkedin.com/pub/david-hahn/78/438/448"> <span class="icon-linkedin2"></span></a>
    </li>

    <li class="icon">
      <a target="_blank" href="http://www.pandora.com/profile/davidmichaelhahn"> <span class="icon-headphones"></span></a>
    </li>

    <li class="icon">
      <a target="_blank" href="#still-to-come"> <span class="icon-pencil"></span></a>
    </li>

    <li class="icon">
      <a target="_blank" href="mailto:davidmichaelhahn@gmail.com"> <span class="icon-mail"></span></a>
    </li>

    <li class="icon">
      <a target="_blank" href="https://www.google.com/calendar/embed?src=david%4040digits.com&ctz=America/Chicago"> <span class="icon-calendar"></span></a>
    </li>
  </ul>
</div>